# Practice

### Rules of Broadcasting
Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:
###### • Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
###### • Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
###### • Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [1]:
import numpy as np

In [8]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
print(a+b, a+5)

[5 6 7] [5 6 7]


In [14]:
M = np.ones((3,3), 'i4')
print(M,'\n\n',M+a)

[[1 1 1]
 [1 1 1]
 [1 1 1]] 

 [[1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
a+b

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### Broadcasting example 1

In [32]:
m = np.ones((2,3))
a = np.arange(3)
print(f'''
m: {m.shape}, {m.dtype} \n{m}\n 
a: {a.shape}, {a.dtype} \n{a}
''')

'''
By Rule 1:
M.shape -> (2, 3)
a.shape -> (1, 3)

By Rule 2:
M.shape -> (2, 3)
a.shape -> (2, 3)

'''
print(f' np.add(m+a): {( c:= m+a ).shape}, {c.dtype} \n{c} ')


m: (2, 3), float64 
[[1. 1. 1.]
 [1. 1. 1.]]
 
a: (3,), int32 
[0 1 2]

 np.add(m+a): (2, 3), float64 
[[1. 2. 3.]
 [1. 2. 3.]] 


#### Broadcasting example 2

In [45]:
a = np.arange(3)[:, np.newaxis]
b = np.arange(3)
print(f'a: {a.shape} \n{a} \n\nb: {b.shape} \n{b}')

'''
Rule 1:
a.shape -> (3, 1)
b.shape -> (1, 3)

Rule 2:
a.shape -> (3, 3)
b.shape -> (3, 3)

'''

print(f'\na+b: {(a+b).shape} \n{a+b}')

a: (3, 1) 
[[0]
 [1]
 [2]] 

b: (3,) 
[0 1 2]

a+b: (3, 3) 
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### Broadcasting example 3

In [50]:
m = np.ones((3,2))
n = np.arange(3)

print(f'm: {m.shape} \n{m} \n\nn: {n.shape} \n{n}')
'''
Rule 1:
M.shape -> (3, 2)
a.shape -> (1, 3)

Rule 2:
M.shape -> (3, 2)
a.shape -> (3, 3)

Rule 3:
the final shapes do not match, so these two arrays are incompatible
'''
m+n

m: (3, 2) 
[[1. 1.]
 [1. 1.]
 [1. 1.]] 

n: (3,) 
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

### Broadcasting in Practice

In [75]:
np.random.seed(0)
x = np.random.random((10,3))
x_mean = x.mean(0)
print(x.shape, x_mean)
x_centered = x - x_mean
print(x_centered.shape, x_centered.mean(0))

(10, 3) [0.52101579 0.62614181 0.59620338]
(10, 3) [1.11022302e-17 1.22124533e-16 3.33066907e-17]


# Task

In [ ]:
import numpy as np

#### ── PART 1 — Broadcasting basics ─────

In [82]:
prices = np.array([100, 200, 300, 400, 500])
print(prices*1.10)

sales = np.array([
    [100, 200, 300],
    [400, 500, 600],
    [700, 800, 900],
])
tax = np.array([0.10, 0.15, 0.20])
'''
sales shape: (3,3)
tax shape:   (1, 3)

Rule 2:
sales shape: (3,3)
tax shape:   (3,3)

'''
sales_tax = sales * (1 + tax)
print(sales_tax.shape, sales_tax)

[110. 220. 330. 440. 550.]
(3, 3) [[ 110.  230.  360.]
 [ 440.  575.  720.]
 [ 770.  920. 1080.]]


#### ── PART 2 — Shapes that work and shapes that fail ─────

In [87]:
a = np.ones((3, 4))
b = np.ones(4)

'''
a: (3,4)
b: (4,)

Rule 1:
a: (3,4)
b: (1,4)

Rule 2:
a: (3,4)
b: (3,4)

'''
print((a+b).shape)

(3, 4)


In [88]:
e = np.ones((3, 4))
f = np.ones((3,)) 

'''
e: (3,4)
f: (3, )

Rule 1:
e: (3,4)
f: (1,3)

Rule 2:
e: (3,4)
f: (3,3)

'''
print((e + f).shape)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

#### ── PART 3 — The reshape trick for column operations ─────

In [94]:
city_discount = np.array([0.10, 0.20, 0.15])
city_discount_col = city_discount[:, np.newaxis]
print( city_discount.shape )

result_col = sales * (1 - city_discount)

'''
sales:         (3,3)
city_discount: (3,1)

Rule 2:
sales:         (3,3)
city_discount: (3,3)

'''
print( result_col, np.shares_memory(city_discount, city_discount_col) )

(3,)
[[ 90. 160. 255.]
 [360. 400. 510.]
 [630. 640. 765.]] True


#### ── PART 4 — Broadcasting in 3D ──────

In [108]:
np.random.seed(0)
data = np.random.randint(1, 100, (5, 4, 3)).astype('f4')
print(data)

metric_means = data.mean(axis=(0,1))
print('\n')
print(metric_means)

normalized_data = data/metric_means
print('\n')
print(normalized_data.shape)
print(normalized_data.mean(axis=(0,1)) )

[[[45. 48. 65.]
  [68. 68. 10.]
  [84. 22. 37.]
  [88. 71. 89.]]

 [[89. 13. 59.]
  [66. 40. 88.]
  [47. 89. 82.]
  [38. 26. 78.]]

 [[73. 10. 21.]
  [81. 70. 80.]
  [48. 65. 83.]
  [89. 50. 30.]]

 [[20. 20. 15.]
  [40. 33. 66.]
  [10. 58. 33.]
  [32. 75. 24.]]

 [[36. 76. 56.]
  [29. 35.  1.]
  [ 1. 37. 54.]
  [ 6. 39. 18.]]]


[49.5  47.25 49.45]


(5, 4, 3)
[1.0000002 1.        1.       ]


#### ── PART 5 — Compounding: views + broadcasting ────

In [115]:
ratings = data[:, :, 2] #view
print(np.shares_memory(data, ratings))

r_min = ratings.min()
r_max = ratings.max()
normalized_ratings = (ratings - r_min) / (r_max - r_min)

print( normalized_ratings.min(), normalized_ratings.max(), 
      np.shares_memory(data, normalized_ratings) ) # False — arithmetic always creates new array

True
0.0 1.0 False


# Project

In [ ]:
import numpy as np

np.random.seed(42)
data = np.random.randint(1, 100,
       size=(5, 4, 3)).astype(np.float64)
data[:, :, 0] *= 0.5    # delivery time
data[:, :, 1] *= 1000   # cost PKR
data[:, :, 2] /= 10     # rating

cities  = ['Lahore', 'Karachi', 'Islamabad', 'Peshawar', 'Quetta']
weeks   = ['Week1', 'Week2', 'Week3', 'Week4']
metrics = ['Delivery_Time', 'Cost_PKR', 'Rating']

#### Task 1 — Broadcasting with shape verification
##### 1. Calculate the mean of each metric across all
##### 2. Subtract metric_means from data using broadcasting
##### 3. Each city has a performance multiplier, Apply this multiplier to each city's delivery time
        city_multipliers = np.array([1.1, 0.9, 1.0, 1.2, 0.8]) 
#####    

In [138]:
metric_means = np.mean(data, axis = (0,1))

print( metric_means.shape, metric_means)
data_sub = data - metric_means
print('\n\n', data_sub.shape, np.shares_memory(data, data_sub), '\n', data_sub)
# shares_memory(data, data_sub) False — arithmetic always creates new array

'''
data:         (5,4,3)
metric_means: (3,)

Rule 1: 
data:         (5,4,3)
metric_means: (1,1,3)

Rule 2:
data:         (5,4,3)
metric_means: (1,4,3)
metric_means: (5,4,3)

'''

# 3. Each city has a performance multiplier:
city_multipliers = np.array(
    [1.1, 0.9, 1.0, 1.2, 0.8])  # shape (5,)


'''
data[:, :, 0]:    (5,4)
city_multipliers: (5,)

Rule 1:
data[:, :, 0]:    (5,4)
city_multipliers: (1,5)

Rule 3 applies here, can't multiple

But with reshape, it can happen

data[:, :, 0]:        (5,4)
city_multipliers_col: (5,1)

Rule 2:
data[:, :, 0]:        (5,4)
city_multipliers_col: (5,4)

'''


city_multipliers_col = city_multipliers[:, np.newaxis]
city_delivery_time = data[:, :, 0] * city_multipliers_col
print('\n', np.shares_memory(city_multipliers_col, city_multipliers), '\n', city_delivery_time )

print('\n\n', city_delivery_time )

(3,) [49.5  47.25 49.45]


 (5, 4, 3) False 
 [[[ -4.5        0.75      15.549999]
  [ 18.5       20.75     -39.45    ]
  [ 34.5      -25.25     -12.450001]
  [ 38.5       23.75      39.55    ]]

 [[ 39.5      -34.25       9.549999]
  [ 16.5       -7.25      38.55    ]
  [ -2.5       41.75      32.55    ]
  [-11.5      -21.25      28.55    ]]

 [[ 23.5      -37.25     -28.45    ]
  [ 31.5       22.75      30.55    ]
  [ -1.5       17.75      33.55    ]
  [ 39.5        2.75     -19.45    ]]

 [[-29.5      -27.25     -34.45    ]
  [ -9.5      -14.25      16.55    ]
  [-39.5       10.75     -16.45    ]
  [-17.5       27.75     -25.45    ]]

 [[-13.5       28.75       6.549999]
  [-20.5      -12.25     -48.45    ]
  [-48.5      -10.25       4.549999]
  [-43.5       -8.25     -31.45    ]]]

 True 
 [[49.5 74.8 92.4 96.8]
 [80.1 59.4 42.3 34.2]
 [73.  81.  48.  89. ]
 [24.  48.  12.  38.4]
 [28.8 23.2  0.8  4.8]]


 [[49.5 74.8 92.4 96.8]
 [80.1 59.4 42.3 34.2]
 [73.  81.  48.  89. ]
 [24.  

### Task 2 — Compounding everything

##### 1. Extract cost data
##### 2. Calculate weekly average cost across all cities

In [158]:
cost = data[:, :, 1] #view

weekly_avg_cost = cost.mean(axis=0)
normalized = cost/weekly_avg_cost
print( normalized.mean(1), normalized.dtype )
citiooos = normalized.mean(1)
boll = normalized.mean(1) > 1
citiooos[boll]


delivery = data[:, :, 0]              # shape (5,4)
city_mult_col = city_multipliers.reshape(-1, 1)  # (5,1)
adjusted = delivery * city_mult_col   # (5,4) ✅

# Verify
print("Lahore original: ", delivery[0])
print("Lahore adjusted: ", adjusted[0])
print("Ratio should be 1.1: ",
      np.round(adjusted[0] / delivery[0], 1))

print("Quetta original: ", delivery[4])
print("Quetta adjusted: ", adjusted[4])
print("Ratio should be 0.8: ",
      np.round(adjusted[4] / delivery[4], 1))

[1.1463242  0.8355951  0.9698204  0.94410664 1.1041536 ] float32
Lahore original:  [45. 68. 84. 88.]
Lahore adjusted:  [49.5 74.8 92.4 96.8]
Ratio should be 1.1:  [1.1 1.1 1.1 1.1]
Quetta original:  [36. 29.  1.  6.]
Quetta adjusted:  [28.8 23.2  0.8  4.8]
Ratio should be 0.8:  [0.8 0.8 0.8 0.8]
