# Practice

## Indexing and Slicing

#### x[start:stop:step]

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5] # here 5 means 6th index cus it starts from 0

5

In [4]:
arr[5:8] # here [5,8), 6th index to 8th index

array([5, 6, 7])

In [5]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [6]:
arr[::2]

array([ 0,  2,  4, 12,  8])

In [7]:
arr[1::2]

array([ 1,  3, 12, 12,  9])

In [8]:
arr[0::2]

array([ 0,  2,  4, 12,  8])

In [9]:
arr_slice = arr[5:8]
arr_slice[0] = 12345
arr 
# even when we assigned the view to diff variable, the changes can be seen in parent np list

array([    0,     1,     2,     3,     4, 12345,    12,    12,     8,
           9])

In [10]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [11]:
arr_slice2 = arr[5:].copy()
arr_slice2[:] = 100_000 # when we use .copy(), it makes new array and changes doesn't effect the parent array
print(arr_slice2)
arr

[100000 100000 100000 100000 100000]


array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [12]:
arr2d = np.array([ [1,2,3,], [4,5,6,], [7,8,9] ])
print('1st Index:', arr2d[0] )
print('3rd Index:', arr2d[2] )
arr2d

1st Index: [1 2 3]
3rd Index: [7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2d[0][2] == arr2d[0, 2]

True

In [14]:
arr2d[0, 2]

3

In [15]:
arr2d[::1, ::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [16]:
arr3d = np.array([ [[1, 2, 3,], [4, 5, 6,]], [[7, 8, 9], [10, 11, 12]] ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
arr3d[1, 0]

array([7, 8, 9])

In [21]:
arr3d[0,1]

array([4, 5, 6])

In [22]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [23]:
x[0]

array([7, 8, 9])

In [24]:
x[0]=23
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[23, 23, 23],
        [10, 11, 12]]])

## Indexing with slices

In [25]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [26]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [27]:
print(arr2d.shape)
arr2d

(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr2d[:2] # axis 0 (row): [0,2)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr2d[:2, :1] # axis 0: [0,2), axis 1: 0

array([[1],
       [4]])

In [30]:
arr2d[:2, :2] # axis 0: [0,2), axis 1: [0: 2)

array([[1, 2],
       [4, 5]])

In [31]:
arr2d[:2, 1:] # axis 0: [0,2), axis 1: [1, end]

array([[2, 3],
       [5, 6]])

In [32]:
lower_dim = arr2d[1, :2]
print(lower_dim.shape)
lower_dim

(2,)


array([4, 5])

In [33]:
lower_dim[0] = 1000
arr2d

array([[   1,    2,    3],
       [1000,    5,    6],
       [   7,    8,    9]])

In [34]:
np.shares_memory(arr2d, lower_dim)

True

In [35]:
print(arr2d)
arr2d[:2, 2]

[[   1    2    3]
 [1000    5    6]
 [   7    8    9]]


array([3, 6])

In [36]:
arr2d[0:, :2] = 0
arr2d

array([[0, 0, 3],
       [0, 0, 6],
       [0, 0, 9]])

## Boolean Indexing

In [37]:
names = np.array( ['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'] )
data = np.array([ [4, 7], [0,2], [-5,6], [0,0], [1,2], [-12,-4], [3,4] ])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [38]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [39]:
bol = names == 'Bob'
print(bol)
data[bol]

[ True False False  True False False False]


array([[4, 7],
       [0, 0]])

In [40]:
bol0 = names == 'Joe'
print(bol0)
data[bol0]

[False  True False False False  True  True]


array([[  0,   2],
       [-12,  -4],
       [  3,   4]])

In [41]:
data[bol, 1:]

array([[7],
       [0]])

In [42]:
data[bol, 1]

array([7, 0])

In [43]:
bol = names != 'Bob'
print(bol)
data[bol]

[False  True  True False  True  True  True]


array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [44]:
bol = ~(names == 'Bob')
print(bol)
data[bol]

[False  True  True False  True  True  True]


array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [45]:
data[~bol]

array([[4, 7],
       [0, 0]])

In [46]:
data[bol, 1]

array([ 2,  6,  2, -4,  4])

In [47]:
data[bol, 1:]

array([[ 2],
       [ 6],
       [ 2],
       [-4],
       [ 4]])

In [48]:
mask = (names == 'Bob') | (names == 'Will') # | is used as OR operator here
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [49]:
mask = (names == 'Bob') & (names == 'Will') # & is used as AND operator here
data[mask]

array([], shape=(0, 2), dtype=int32)

In [50]:
print(data)
data[data > 2]

[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


array([4, 7, 6, 3, 4])

In [51]:
data[names != 'Joe'] = 7
data

array([[  7,   7],
       [  0,   2],
       [  7,   7],
       [  7,   7],
       [  7,   7],
       [-12,  -4],
       [  3,   4]])

## Fancy Indexing

In [52]:
arr = np.zeros((8, 4), 'i4')
for i in range(8):
    arr[i] = i
    
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [53]:
arr_sli = arr[[4,3,0,6]]
arr_sli

array([[4, 4, 4, 4],
       [3, 3, 3, 3],
       [0, 0, 0, 0],
       [6, 6, 6, 6]])

In [54]:
np.shares_memory(arr, arr_sli)

False

In [55]:
arr[[-3, -5, -7]]

array([[5, 5, 5, 5],
       [3, 3, 3, 3],
       [1, 1, 1, 1]])

In [56]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [57]:
arr[[1, 5, 7, 2], [0, 3, 1, 2] ]

array([ 4, 23, 29, 10])

In [58]:
arr[[1, 5, 7, 2], [0, 3, 1] ] # one critical notice: indexing arraus should be of same shape

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (3,) 

In [59]:
arr[[1, 5, 7], [0, 3, 1] ] 

array([ 4, 23, 29])

In [60]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [61]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [62]:
print( f'''Notice the differnce here:
1.\n {arr[[1, 5, 7, 2], [0, 3, 1, 2]]}, 
2.\n {arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] }
''')

Notice the differnce here:
1.
 [ 4 23 29 10], 
2.
 [[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]



## Transposing Arrays

In [63]:
arr = np.arange(15).reshape((3, 5))
print(arr)
arr.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [64]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [65]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [66]:
arr.T @ arr # @ works same as 'np.dot'

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [67]:
arr1 = np.arange(40).reshape((4, 2, 5))
print(arr1.shape)
arr1

(4, 2, 5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [68]:
print(arr1.T.shape)
arr1.T

(5, 2, 4)


array([[[ 0, 10, 20, 30],
        [ 5, 15, 25, 35]],

       [[ 1, 11, 21, 31],
        [ 6, 16, 26, 36]],

       [[ 2, 12, 22, 32],
        [ 7, 17, 27, 37]],

       [[ 3, 13, 23, 33],
        [ 8, 18, 28, 38]],

       [[ 4, 14, 24, 34],
        [ 9, 19, 29, 39]]])

In [69]:
print(arr1,'\n-------------------------------')
print( arr1.swapaxes(0, 2) )
# swapaxes uses 2 parameter to swap like here axis 0 and axis 2 will be swapped with each other

'''
axis 0: block
axis 1: rows
axis 2: column

'''

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]] 
-------------------------------
[[[ 0 10 20 30]
  [ 5 15 25 35]]

 [[ 1 11 21 31]
  [ 6 16 26 36]]

 [[ 2 12 22 32]
  [ 7 17 27 37]]

 [[ 3 13 23 33]
  [ 8 18 28 38]]

 [[ 4 14 24 34]
  [ 9 19 29 39]]]


'\naxis 0: block\naxis 1: rows\naxis 2: column\n\n'

In [70]:
arr2 = np.arange(8).reshape(2,2,2)
arr2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [71]:
arr2.swapaxes(0, 1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [72]:
# arr1.swapaxes(0, 2).shape 
arr1.swapaxes(0, 2)

array([[[ 0, 10, 20, 30],
        [ 5, 15, 25, 35]],

       [[ 1, 11, 21, 31],
        [ 6, 16, 26, 36]],

       [[ 2, 12, 22, 32],
        [ 7, 17, 27, 37]],

       [[ 3, 13, 23, 33],
        [ 8, 18, 28, 38]],

       [[ 4, 14, 24, 34],
        [ 9, 19, 29, 39]]])

In [73]:
# arr1.swapaxes(0, 1).shape
arr1.swapaxes(0, 1)

array([[[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34]],

       [[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39]]])

In [74]:
# arr1.swapaxes(1, 2).shape
arr1.swapaxes(1, 2)

array([[[ 0,  5],
        [ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9]],

       [[10, 15],
        [11, 16],
        [12, 17],
        [13, 18],
        [14, 19]],

       [[20, 25],
        [21, 26],
        [22, 27],
        [23, 28],
        [24, 29]],

       [[30, 35],
        [31, 36],
        [32, 37],
        [33, 38],
        [34, 39]]])

In [75]:
arr1 = np.arange(40).reshape((4, 2, 5))
print(arr1) 
print( '-------------------\n',arr1.reshape(5, 2, 4).shape == arr1.swapaxes(0, 2).shape )
# reshape — reorganises elements into new groupings
print( '-------------------\n',arr1.reshape(5, 2, 4) )
# swapaxes — rotates the cube, elements keep their relationships
print( '-------------------\n',arr1.swapaxes(0, 2) )

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]]
-------------------
 True
-------------------
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]]
-------------------
 [[[ 0 10 20 30]
  [ 5 15 25 35]]

 [[ 1 11 21 31]
  [ 6 16 26 36]]

 [[ 2 12 22 32]
  [ 7 17 27 37]]

 [[ 3 13 23 33]
  [ 8 18 28 38]]

 [[ 4 14 24 34]
  [ 9 19 29 39]]]


# Tasks

### ── PART 1 — 1D Indexing & Slicing ────

In [91]:
import numpy as np
prices = np.array([ 100, 200, 300, 400, 500, 600, 700, 800 ])
# print(prices[:])
print(prices[0])
print(prices[-1])
print(prices[2:5])
print(prices[:3])
print(prices[5:])
print(prices[::2])
print(prices[::-1])

100
800
[300 400 500]
[100 200 300]
[600 700 800]
[100 300 500 700]
[800 700 600 500 400 300 200 100]


In [92]:
slice_a = prices[2:5]
np.shares_memory(prices, slice_a)

True

In [93]:
slice_a[0] = 9999
prices

array([ 100,  200, 9999,  400,  500,  600,  700,  800])

### ── PART 2 — 2D Indexing ──

In [100]:
sales = np.array([
    [100, 200, 300],
    [400, 500, 600],
    [700, 800, 900]
])

print( sales[0] )
print( sales [1, 2] )
print( sales[:, 1] )
print( sales[1:, :2] )

row = sales[1]
np.shares_memory(sales, row)

[100 200 300]
600
[200 500 800]
[[400 500]
 [700 800]]


True

### ── PART 3 — Views vs Copies — The Full Picture ───

In [104]:
original = np.array( [10, 20, 30, 40, 50] )
view = original[1:4]
print( np.shares_memory(original, view) )
view[0] = 999
original

True


array([ 10, 999,  30,  40,  50])

In [110]:
original2 = np.array( [10, 20, 30, 40, 50] )
safe_copy = original[1:4]
# safe_copy = original[[1,2,3]]
np.shares_memory(original2, safe_copy)
safe_copy[0] = 999
original2

array([10, 20, 30, 40, 50])

In [113]:
original3 = np.array( [10, 20, 30, 40, 50] )
bool_results = original3[ original3 > 25 ]
print(bool_results)
np.shares_memory(original3, bool_results)

[30 40 50]


False

In [114]:
fancy_result = original3[[0,2,4]]
np.shares_memory(original3, fancy_result)

False

### ── PART 4 — Reshaping ─────

In [128]:
flat = np.arange(12)
matrix = flat.reshape(3,4)
print( np.shares_memory(flat, matrix) )
matrix[0, 0] = 9999
print(flat)

True
[9999    1    2    3    4    5    6    7    8    9   10   11]


In [127]:
col_vector = flat.reshape(-1, 1)
row_vector = flat.reshape(1, -1)
print( col_vector, row_vector )

[[9999]
 [   1]
 [   2]
 [   3]
 [   4]
 [   5]
 [   6]
 [   7]
 [   8]
 [   9]
 [  10]
 [  11]] [[9999    1    2    3    4    5    6    7    8    9   10   11]]


In [138]:
matrix2 = np.arange(12).reshape(3,4)
print('Matrix Shape:', matrix2.shape)
T = matrix2.T
print('Matrix Transpose Shape:', T.shape)
print('View?', np.shares_memory(matrix2, T) )
matrix2 @ T

Matrix Shape: (3, 4)
Matrix Transpose Shape: (4, 3)
View? True


array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [145]:
ravelled  = matrix2.ravel()
flattened = matrix2.flatten()
#Both take a multi-dimensional array and return a flat 1D array.

print(ravelled, np.shares_memory(matrix2, ravelled))    # True
print(flattened, np.shares_memory(matrix2, flattened))   # False

[ 0  1  2  3  4  5  6  7  8  9 10 11] True
[ 0  1  2  3  4  5  6  7  8  9 10 11] False


### ── PART 5 — Fancy Indexing ─────

In [151]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80])
indices = [0, 3, 6]
selected = data[indices]
print(selected, selected.dtype)
np.shares_memory(data, selected)

[10 40 70] int32


False

In [148]:
matrix3 = np.arange(16).reshape(4,4)
print( matrix3[[0,2]] )
print( matrix3[[0, 1], [2, 3]] )

[[ 0  1  2  3]
 [ 8  9 10 11]]
[2 7]


# Project 

In [191]:
import numpy as np

np.random.seed(42)
sales = np.random.randint(500, 5000, size=(4, 3, 4))

product_names = ['Shirts', 'Shoes', 'Bags', 'Watches']
regions       = ['North', 'Central', 'South']
quarters      = ['Q1', 'Q2', 'Q3', 'Q4']

product_names = np.array(product_names)
regions = np.array(regions)
quarters = np.array(quarters)

### Task 1 — Indexing with engineering checkst change"

Extract each of the following:

a) All sales for Shirts across all regions and quarters
    
b) Q1 sales only for all products and all regions
    
c) Sales for Bags in Central region across all quarters
        
d) Single value — Watches, South, Q4

In [192]:
print( f'\tSales: \n\n{sales[:]}\n---------------------------------') #view, no additional computation power but can;t lose sales data otyherwise dire conquences
print('\n\tSales for Q1\n', sales[quarters == 'Q1'] ) #copy, takes extra computation power
print('\n\tSales for Bag\n', sales[product_names == 'Bags'] ) #copy, takes extra computation power
print('\n\tSales: Watches, South, Q4', sales[3,2,3]) #view, no additional computation cost but cant lose sales

	Sales: 

[[[1360 4272 3592  966]
  [4926 3944 3671 3419]
  [ 630 2185 1269 2891]]

 [[2933 1684 3885 4617]
  [3404  974 1582 3058]
  [2547 3247 1475 2306]]

 [[ 689 3234 3505 2399]
  [1767 2028 3702 4056]
  [4390 1146 3388 2935]]

 [[1100 2863 2561  741]
  [2541 3324 3112 1863]
  [1978 3056 1275 4514]]]
---------------------------------

	Sales for Q1
 [[[1360 4272 3592  966]
  [4926 3944 3671 3419]
  [ 630 2185 1269 2891]]]

	Sales for Bag
 [[[ 689 3234 3505 2399]
  [1767 2028 3702 4056]
  [4390 1146 3388 2935]]]

	Sales: Watches, South, Q4 4514


### Task 2 — The Pipeline Corruption Bug

def normalize_product(product_slice):
    
    product_slice -= product_slice.min()
    
    return product_slice

shirts = sales[0]

normalized = normalize_product(shirts)

##### rewrite normalize_product so it can never corrupt the original.

In [225]:
# here sales[0] is a view assigned to shirts, changes in the later gonna effect original
# with lil tweak, we can prevent original file corruption

def normalize_product(product_slice):
    arr = product_slice.copy()
    arr -= arr.min()
    return arr

normalized = normalize_product(shirts)
print(normalized)
sales

[[ 730 3642 2962  336]
 [4296 3314 3041 2789]
 [   0 1555  639 2261]]


array([[[1360, 4272, 3592,  966],
        [4926, 3944, 3671, 3419],
        [ 630, 2185, 1269,    0]],

       [[2933, 1684, 3885,    0],
        [3404,  974, 1582,    0],
        [2547, 3247, 1475, 2306]],

       [[ 689, 3234, 3505, 2399],
        [1767, 2028, 3702, 4056],
        [4390, 1146, 3388, 2935]],

       [[1100, 2863, 2561,  741],
        [2541, 3324, 3112, 1863],
        [1978, 3056, 1275, 4514]]])

#### In a production ML pipeline processing 10 million rows, which is more expensive — the memory cost of .copy() or the debugging cost of a silent data corruption bug? Write your answer as a comment.

##### Response: its more expensive to get to the original data cus cost of messing original data is far more than the cost of processing. 

### Task 3 — Reshaping For ML

In [203]:
sales_2d = sales.reshape(12,4)
print(sales_2d.shape)
print(np.shares_memory(sales, sales_2d) )

(12, 4)
True


#### if a preprocessing function modifies sales_2d in place, does the original sales array get corrupted? Prove it with code — do not just predict.

In [210]:
print(sales, '\n-------------------------------\n')
print(sales_2d, '\n-------------------------------\n')
sales_2d[2:5, -1] = 0
print(sales, '\n-------------------------------\n')
np.shares_memory(sales, sales_2d)

[[[1360 4272 3592  966]
  [4926 3944 3671 3419]
  [ 630 2185 1269    0]]

 [[2933 1684 3885    0]
  [3404  974 1582    0]
  [2547 3247 1475 2306]]

 [[ 689 3234 3505 2399]
  [1767 2028 3702 4056]
  [4390 1146 3388 2935]]

 [[1100 2863 2561  741]
  [2541 3324 3112 1863]
  [1978 3056 1275 4514]]] 
-------------------------------

[[1360 4272 3592  966]
 [4926 3944 3671 3419]
 [ 630 2185 1269    0]
 [2933 1684 3885    0]
 [3404  974 1582    0]
 [2547 3247 1475 2306]
 [ 689 3234 3505 2399]
 [1767 2028 3702 4056]
 [4390 1146 3388 2935]
 [1100 2863 2561  741]
 [2541 3324 3112 1863]
 [1978 3056 1275 4514]] 
-------------------------------

[[[1360 4272 3592  966]
  [4926 3944 3671 3419]
  [ 630 2185 1269    0]]

 [[2933 1684 3885    0]
  [3404  974 1582    0]
  [2547 3247 1475 2306]]

 [[ 689 3234 3505 2399]
  [1767 2028 3702 4056]
  [4390 1146 3388 2935]]

 [[1100 2863 2561  741]
  [2541 3324 3112 1863]
  [1978 3056 1275 4514]]] 
-------------------------------



True

##### Show how to reshape safely so in-place modifications cannot reach the original

In [211]:
sales_2d_copy = sales.reshape(12,4).copy()
np.shares_memory(sales, sales_2d_copy)

False

### Task 4 — Boolean indexing with dtype audit

Using sales_2d to find 

1. All rows where Q1 sales were above 2000
2. Count how many such rows
3. Calculate average Q1 sales for those rows only
4. Find which rows had ANY quarter above 4500

In [220]:
sales_2000 = sales > 2000 # boolean dtype
sales_above_2000 = sales[sales_2000]
print( sales_above_2000,  sales_above_2000.dtype ) # same dtype, nothing gonna change 
print( sales_2000.sum(), sales_2000.sum().dtype ) # same dtype, nothing gonna change 
print( np.round(sales_above_2000.mean()).astype(np.int32) ) # its gonna change to float64 but I have changed it to 'i4'
print( sales[sales > 4500] ) # same dtype, nothing gonna change 

[4272 3592 4926 3944 3671 3419 2185 2933 3885 3404 2547 3247 2306 3234
 3505 2399 2028 3702 4056 4390 3388 2935 2863 2561 2541 3324 3112 3056
 4514] int32
29 int32
3308
[4926 4514]
