In [2]:
import numpy as np

## Dtype Casting

In [3]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [9]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [12]:
str_arr = float_arr.astype(np.string_)
str_arr

array([b'1.0', b'2.0', b'3.0', b'4.0', b'5.0'], dtype='|S32')

In [17]:
str_arr1 = arr.astype(np.string_) # never use string_, instead do str or str_
str_arr1

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S11')

In [15]:
readable = str_arr.astype(str)
readable

array(['1.0', '2.0', '3.0', '4.0', '5.0'], dtype='<U32')

In [29]:
arr2 = str_arr.astype(np.float32) # cant directly change to int cus of float value
arr3 = arr2.astype(np.int8) # thats why first convert convert to float, then drop the decimal value
print(arr3)
arr3.dtype

[1 2 3 4 5]


dtype('int8')

In [30]:
arr = np.array([3.7, -1.2, -2.6, .5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [33]:
arr.astype(np.int8)

array([ 3, -1, -2,  0, 12, 10], dtype=int8)

In [46]:
numeric_str = np.array(['1.25', '-9.6', '42'], np.str_)
print(numeric_str, '\n---------------------------------')

numeric = numeric_str.astype(np.float64)
print(numeric)
numeric.dtype

arr = numeric.astype(np.int8)
arr

['1.25' '-9.6' '42'] 
---------------------------------
[ 1.25 -9.6  42.  ]


array([ 1, -9, 42], dtype=int8)

In [50]:
int_arr = np.arange(10)
caliber = np.array([.22, .270, .380, .44, 50], np.float32)
int_arr.astype(caliber.dtype)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [55]:
zeros_uint32 = np.zeros(8, "f4")
zeros_uint32

array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

## Arithmetic with NumPy Arrays: UFuncs

In [57]:
arr = np.array([ [1., 2., 3.], [4., 5., 6.] ])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [59]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [60]:
arr**arr

array([[1.0000e+00, 4.0000e+00, 2.7000e+01],
       [2.5600e+02, 3.1250e+03, 4.6656e+04]])

In [61]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
arr+arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [63]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [65]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [72]:
arr2 = np.array([ [0., 4., 1.], [7., 2., 12.] ])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [77]:
mask = arr > arr2
print(mask)
arr2[mask]

[[ True False  True]
 [False  True False]]


array([0., 1., 2.])

In [105]:
arr/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [106]:
arr//3

array([[0., 0., 1.],
       [1., 1., 2.]])

In [107]:
arr%3

array([[1., 2., 0.],
       [1., 2., 0.]])

In [114]:
x = np.arange(-5,5)
print(x)
abs(x)

[-5 -4 -3 -2 -1  0  1  2  3  4]


array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

In [117]:
np.absolute(x)
np.abs(x)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

In [115]:
set(abs(x))

{0, 1, 2, 3, 4, 5}

In [119]:
# This ufunc can also handle complex data, in which the absolute value returns the magnitude
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j]) 
np.abs(x)

array([5., 5., 2., 1.])

In [128]:
theta = np.linspace(0, np.pi, 4)
print("theta      =", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      = [0.         1.04719755 2.0943951  3.14159265]
sin(theta) =  [0.00000000e+00 8.66025404e-01 8.66025404e-01 1.22464680e-16]
cos(theta) =  [ 1.   0.5 -0.5 -1. ]
tan(theta) =  [ 0.00000000e+00  1.73205081e+00 -1.73205081e+00 -1.22464680e-16]


In [130]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [129]:
# np.random.seed(0)
np.random.randint(1,10, 10) # Create a 1x10 array of random integers in the interval [1, 10)
np.random.randint(1,10, (10,1) ) # Create a 10x1 array of random integers in the interval [1, 10)

array([[7],
       [9],
       [9],
       [2],
       [7],
       [8],
       [8],
       [9],
       [2],
       [6]])

In [87]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.33744563, 0.12123776, 0.58749277],
       [0.17885509, 0.62204332, 0.91685981],
       [0.96384604, 0.61009935, 0.65910977]])

In [88]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.00281978,  0.26190852,  2.63889134],
       [-1.19124564,  1.65736382, -0.99447861],
       [ 0.22127611, -0.46005185, -0.4986745 ]])

In [98]:
np.random.seed(0)
np.random.randint(1,10, (1,2))

array([[6, 1]])

## Guided Task

 ── PART 1 — Basic arithmetic between arrays ──────────

In [140]:
a = np.array([10, 20, 30, 40], np.int16)
b = np.array([1, 2, 3, 4], np.int16)
add = a+b
sub = a-b
mul = a*b
div = a/b
floor = a//b
square = a**2
power = a**b
print('Add:         ',add, add.dtype)
print('Substract:   ', sub, sub.dtype)
print('Multiply:    ', mul, mul.dtype)
print('Divide:      ', div, div.dtype)
print('Floor:       ', floor, floor.dtype)
print('Square:      ', square, square.dtype)
print('Power:       ', power, power.dtype)

Add:          [11 22 33 44] int16
Substract:    [ 9 18 27 36] int16
Multiply:     [ 10  40  90 160] int16
Divide:       [10. 10. 10. 10.] float64
Floor:        [10 10 10 10] int16
Square:       [ 100  400  900 1600] int16
Power:        [   10   400 27000  4096] int16


 ── PART 2 — Scalar operations ──────────

In [158]:
# audit the data type
sales = np.array([1000, 1500, 1200, 1800], np.int32)
with_tax = sales * 1.15 # Apply 15% tax,
print(with_tax, with_tax.dtype)

with_tax = (sales * 1.15).astype(np.float32) # Apply 15% tax,
print(with_tax, with_tax.dtype)

with_tax_f4 = with_tax.astype('f4')
print(with_tax_f4, with_tax_f4.dtype)

with_tax_f32 = sales * np.float32(1.15) # dtype should have been float32 but technical error
print(with_tax_f32, with_tax_f32.dtype)

with_tax_f32 = sales.astype(np.float32) * np.float32(1.15) # np.float32 = 'f4'
print(with_tax_f32, with_tax_f32.dtype)

[1150. 1725. 1380. 2070.] float64
[1150. 1725. 1380. 2070.] float32
[1150. 1725. 1380. 2070.] float32
[1149.99997616 1724.99996424 1379.99997139 2069.99995708] float64
[1150. 1725. 1380. 2070.] float32


 ── PART 3 — The silent upcasting rule ─────────

In [163]:
x = np.arange(6,)
y=np.arange(7,13).astype(np.float64)
z = x+y
print('x:', x.dtype)
print('y:', y.dtype)
print('z:', z, z.dtype)

# int8 + float64 = float64, numpy always upcast to highest precision

x: int32
y: float64
z: [ 7.  9. 11. 13. 15. 17.] float64


── PART 4 — Comparison operations ────

In [170]:
scores = np.array([45, 82, 91, 33, 76, 88], 'i2')
threshold = scores > 75
scores[threshold]

passed = threshold.sum()
print(f'Students who passed: {passed}')

Students who passed: 4


# Project

In [180]:
import numpy as np
revenue = np.array([320, 415, 390, 502, 478, 610])
costs = np.array([210, 280, 260, 310, 305, 390])

Profit for each month: [110 135 130 192 173 220]
Total profit across all months: 960
Average Monthly profit: 160
Highest monthly profit: 220
Lowest monthly profit: 110


### Task 1 — Profit analysis
Calculate and print:

Monthly profit for each month (one operation)
Total profit across all 6 months
Average monthly profit
Best month profit and worst month profit

No loops. One NumPy operation per answer.

In [181]:
profit = revenue - costs
print(f'Profit for each month: {profit}')

bi_annualy_profit = profit.sum()
print(f'Total profit across all months: {bi_annualy_profit}')

# avg_monthly_profit = bi_annualy_profit/revenue.size
avg_monthly_profit = np.round(profit.mean()).astype('i4')
print(f'Average Monthly profit: {avg_monthly_profit}')

print(f'Highest monthly profit: {profit.max()}')
print(f'Lowest monthly profit: {profit.min()}')

Profit for each month: [110 135 130 192 173 220]
Total profit across all months: 960
Average Monthly profit: 160
Highest monthly profit: 220
Lowest monthly profit: 110


### Task 2 — The silent upcast trap
fix it so the output is float32 instead of float64. Show the memory saving using nbytes

In [208]:
tax_rate = 0.17
revenue_after_tax = revenue * tax_rate
bytes_used = revenue_after_tax.nbytes
print(revenue_after_tax.dtype)
print(bytes_used)
# be default tax_rate is float64 or 'f8' and its gonna take almost double the memory space allocated

revenue_after_tax_f4 = np.float32(revenue) * np.float32(tax_rate)
bytes_new = revenue_after_tax_f4.nbytes
print(revenue_after_tax_f4.dtype)
print(bytes_new)

print(f'Saved Memory: {bytes_used-bytes_new}')


float64
48
float32
24
Saved Memory: 24


### Task 3 — Boolean filtering
Using the revenue and costs arrays:

Find which months had profit greater than 150 (thousand PKR)
Count how many such months there were
Find what percentage of months were high-profit months

All in NumPy. No loops. No if statements.

In [201]:
threshold = profit > 150
high_profit_months = profit[threshold]
count = threshold.sum()
print(f'Profit Months > 150k: {high_profit_months}')
print(f'Total Months > 150k: {count}')

percentage = ( count/len(profit) )*100
print(f"Percentage: {percentage}%") 

Profit Months > 150k: [192 173 220]
Total Months > 150k: 3
Percentage: 50.0%


In [187]:
import numpy as np

arr_f64 = np.ones(1_000_000, dtype=np.float64)
arr_f32 = np.ones(1_000_000, dtype=np.float32)

print(f"float64: {arr_f64.nbytes / 1e6:.1f} MB")
print(f"float32: {arr_f32.nbytes / 1e6:.1f} MB")

float64: 8.0 MB
float32: 4.0 MB
