# Practice

### Sorting

In [2]:
import numpy as np

In [65]:
rng = np.random.default_rng(42)
arr = rng.standard_normal(6)
arr2 = rng.standard_normal((5,3))
print(f'''
arr: \n{arr}

sort(arr): \n{ np.sort(arr) }

arr2: \n{arr2}

sort(arr2): Vertical \n{ np.sort(arr2, axis=0) }  

sort(arr2): Horizontal \n{ np.sort(arr2, axis=1) }  

''')


arr: 
[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951]

sort(arr): 
[-1.95103519 -1.30217951 -1.03998411  0.30471708  0.7504512   0.94056472]

arr2: 
[[ 0.1278404  -0.31624259 -0.01680116]
 [-0.85304393  0.87939797  0.77779194]
 [ 0.0660307   1.12724121  0.46750934]
 [-0.85929246  0.36875078 -0.9588826 ]
 [ 0.8784503  -0.04992591 -0.18486236]]

sort(arr2): Vertical 
[[-0.85929246 -0.31624259 -0.9588826 ]
 [-0.85304393 -0.04992591 -0.18486236]
 [ 0.0660307   0.36875078 -0.01680116]
 [ 0.1278404   0.87939797  0.46750934]
 [ 0.8784503   1.12724121  0.77779194]]  

sort(arr2): Horizontal 
[[-0.31624259 -0.01680116  0.1278404 ]
 [-0.85304393  0.77779194  0.87939797]
 [ 0.0660307   0.46750934  1.12724121]
 [-0.9588826  -0.85929246  0.36875078]
 [-0.18486236 -0.04992591  0.8784503 ]]  




In [23]:
np.sort(arr)

array([-1.95103519, -1.30217951, -1.03998411,  0.30471708,  0.7504512 ,
        0.94056472])

In [34]:
arr3 = np.array([
    [ 0.936 , 1.2385, 1.2728],
    [ 0.4059, -0.0503, 0.2893],
    [ 0.1793, 1.3975, 0.292 ],
    [ 0.6384, -0.0279, 1.3711],
    [-2.0528, 0.3805, 0.7554] 
])

np.sort(arr3, axis = 0)

array([[-2.0528, -0.0503,  0.2893],
       [ 0.1793, -0.0279,  0.292 ],
       [ 0.4059,  0.3805,  0.7554],
       [ 0.6384,  1.2385,  1.2728],
       [ 0.936 ,  1.3975,  1.3711]])

In [62]:
np.random.seed(30)
arr4 = np.random.randint(-10,10, size =(3,2,2))
print(f' {arr4}, \n**************\n{np.sort(arr4, axis = 0)} ')

 [[[-5 -5]
  [ 3  3]]

 [[ 2 -8]
  [ 7  4]]

 [[-7 -1]
  [-3 -9]]], 
**************
[[[-7 -8]
  [-3 -9]]

 [[-5 -5]
  [ 3  3]]

 [[ 2 -1]
  [ 7  4]]] 


In [82]:
print(f'''
argsort: argsort shows index, not elements

{arr} 

{np.argsort(arr)}

{( c:= np.argsort(arr)[::-1] )} 

Sorted by top elements:
{arr[c]}
''')


argsort: argsort shows index, not elements

[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951] 

[4 5 1 0 2 3]

[3 2 0 1 5 4] 

Sorted by top elements:
[ 0.94056472  0.7504512   0.30471708 -1.03998411 -1.30217951 -1.95103519]



### Unique and Other Set Logic

##### np.union1d performs a Set Union.

###### 1. It gathers all elements from both arrays.

###### 2. It De-duplicates them (removes repeats).

###### 3. It Sorts them.

##### np.in1d(x, y) 

###### Compute a Boolean array indicating whether each element of x is contained in y

In [226]:
''''
Company made 2 campigns to increase their sales and see the value it brings. 
Campaign_members has data of participants and 
Employ_id has data of employee ids involved in the campaign.
'''

campaign1_members = np.array(['Bob', 'Joe', 'Bob', 'Will', 'Joe', 'Bob'])
campaign2_members = np.array(['Joe', 'King', 'Bob', 'King'])
blacklisted_members = np.array(['King'])

employ_id_1 = np.array([1, 2, 3, 2, 3, 4, 5, 5, 4, 6])
employ_id_2 = np.array([1, 3, 5, 6, 2, 3, 5, 8, 9, 10])

all_members = np.union1d(campaign1_members, campaign2_members)
both_campaign_members = np.intersect1d(campaign1_members, campaign2_members)
mask = np.in1d(all_members, blacklisted_members) # to remove blacklisted members

all_employees = np.union1d(employ_id_1, employ_id_2)
both_campaign_employees = np.intersect1d(employ_id_1, employ_id_2)

print(f'''
Participants of both campaigns: {all_members}
Loyal Customers:{both_campaign_members}
Unique Names: {np.unique(campaign1_members)}
Verified Participants: {all_members[~mask] }

All involved Employees: {all_employees}
Special Reward Employees:{both_campaign_employees}
Unique Employees: {np.unique(employ_id_1)}

''')


Participants of both campaigns: ['Bob' 'Joe' 'King' 'Will']
Loyal Customers:['Bob' 'Joe']
Unique Names: ['Bob' 'Joe' 'Will']
Verified Participants: ['Bob' 'Joe' 'Will']

All involved Employees: [ 1  2  3  4  5  6  8  9 10]
Special Reward Employees:[1 2 3 5 6]
Unique Employees: [1 2 3 4 5 6]




# Task

In [117]:
import numpy as np

#### ── PART 1 — Sorting ─────

In [155]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
sorted_arr = np.sort(arr)
top_arr = np.argsort(arr)[::-1]
print(f'''
array: {arr}
sorted array: {sorted_arr}, {np.shares_memory(arr, sorted_arr)}
top array: {arr[top_arr]}, {np.shares_memory(arr, top_arr)}
''')

arr_copy = arr.copy()
arr_copy.sort()
print(arr_copy, np.shares_memory(arr, arr_copy) )

scores = np.array([85, 92, 78, 95, 88])
rank_indicies = np.argsort(scores)[::-1]
print('\nRanked scores:', rank_indicies)

names = np.array(['Ali', 'Sara', 'Umar', 'Zara', 'Bilal'])
print(f'{names[rank_indicies]} \n{scores[rank_indicies]}')


matrix = np.array([[3, 1, 4],
                   [1, 5, 9],
                   [2, 6, 5]])
print(f'''
sort each COLUMN \n{np.sort(matrix, axis=0)}

sort each ROW \n{np.sort(matrix, axis=1)}
''')


array: [3 1 4 1 5 9 2 6]
sorted array: [1 1 2 3 4 5 6 9], False
top array: [9 6 5 4 3 2 1 1], False

[1 1 2 3 4 5 6 9] False

Ranked scores: [3 1 4 0 2]
['Zara' 'Sara' 'Bilal' 'Ali' 'Umar'] 
[95 92 88 85 78]

sort each COLUMN 
[[1 1 4]
 [2 5 5]
 [3 6 9]]

sort each ROW 
[[1 3 4]
 [1 5 9]
 [2 5 6]]



#### ── PART 2 — Searching ────

In [169]:
data = np.array([1, -2, 3, -4, 5, -6])

#where(condition, if_true, if_false)
result = np.where(data >0, data, 0)
print(result)

indicies = np.where(data>0)
final = result[indicies] # gonna store/print non-zeros elemets in result array
print( final, np.shares_memory(final, result) )

# np.searchsorted — find insertion point in sorted array
sorted_data = np.array([10, 20, 30, 40, 50])
print(f'''
{ np.searchsorted(sorted_data, 25) }
{ np.searchsorted(sorted_data, [25, 35]) }
''')

# np.argmax / np.argmin — index of max/min
print( np.argmax(sorted_data), np.argmin(sorted_data) )

[1 0 3 0 5 0]
[1 3 5] False

2
[2 3]

4 0


##### np.searchsorted(data, 25) $\rightarrow$ 2
Value 25 is greater than 20 (Index 1) but less than 30 (Index 2).To keep the order, 25 "pushes" 30 aside and takes Index 2.

##### np.searchsorted(data, [25, 35]) $\rightarrow$ [2, 3]
For 25: It belongs at Index 2.For 35: It belongs between 30 (Index 2) and 40 (Index 3). It takes Index 3.

#### ── PART 3 — Set operations ───

In [180]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

print(f'''
unique a: {np.unique(a)}
unique b: {np.unique(b)}

union (a, b): {np.union1d(a, b)}
intersect(a, b): {np.intersect1d(a,b)}

'Compute a Boolean array indicating whether each element of a is contained in b'
bool: {np.in1d(a, b)} 

''')


unique a: [1 2 3 4 5]
unique b: [3 4 5 6 7]

union (a, b): [1 2 3 4 5 6 7]
intersect(a, b): [3 4 5]

'Compute a Boolean array indicating whether each element of a is contained in b'
bool: [False False  True  True  True] 


[1 2 3 4 5 6 9]
[2 1 2 1 2 1 1]


In [198]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
'''
NumPy scans your array and builds a Reference Key (unique) and a Scorecard (counts).

Task 1 (Unique): It identifies every distinct number, removes duplicates, and sorts them.

Task 2 (Counts): It goes back through the original array and tallies how many times each number in your "Reference Key" appeared.
'''
unique, counts = np.unique(arr, return_counts=True)
print(unique)    # [1 2 3 4 5 6 9]
print(counts)    # [2 1 2 1 2 1 1] — how many of each

duplicate = counts>1
print(duplicate)
print(unique[duplicate])

[1 2 3 4 5 6 9]
[2 1 2 1 2 1 1]
[ True False  True False  True False False]
[1 3 5]


#### ── PART 4 — Missing data with np.nan ───

In [225]:
data = np.array([1.0, np.nan, 3.0, np.nan, 5.0], 'f8')
print(f'''
\t***Regular Operations***

Mean: {np.mean(data)}
Sum: {np.sum(data)}
bool: {np.isnan(data)}
nan: {np.isnan(data).sum()}

\t***nan-safe operations***
Mean: {np.nanmean(data):.0f}
Sum: {np.nansum(data):.1f}
Min: {np.nanmin(data)}
Max: {np.nanmax(data)}

''')

mask = np.isnan(data)
print(data[mask])
data[mask] = np.nanmean(data)
print(data)


	***Regular Operations***

Mean: nan
Sum: nan
bool: [False  True False  True False]
nan: 2

	***nan-safe operations***
Mean: 3
Sum: 9.0
Min: 1.0
Max: 5.0


[nan nan]
[1. 3. 3. 3. 5.]
