In [23]:
import numpy as np

In [24]:
data = [ [0, 1,2,3,4], [5,6,7,8, 9] ]
arr = np.array(data)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
arr * 10

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [26]:
arr + arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [27]:
arr.shape

(2, 5)

In [28]:
arr.dtype

dtype('int32')

In [29]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr1.shape

(5,)

In [34]:
data2 = [ [1,2,3,4,], [5,6,7,8,] ]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
arr2.shape

(2, 4)

In [37]:
arr2.ndim

2

In [40]:
arr2.dtype

dtype('int32')

In [41]:
arr1.dtype

dtype('float64')

In [52]:
np.zeros(10, np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [48]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [53]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
np.empty(3)

array([0., 0., 0.])

In [59]:
np.empty((2, 3, 2))

array([[[1.35555333e-311, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.18831764e-312, 1.04082753e-047]],

       [[4.26974957e-090, 1.83119717e-076],
        [1.52471830e-052, 2.12581920e+160],
        [6.48224659e+170, 4.93432906e+257]]])

In [60]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [65]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
'''
np.asarray() — The Lazy Converter

Same as np.array() but smarter — if the input is already a NumPy array, 
it does nothing. No copy, no new buffer. Saves memory.
'''

'\nnp.asarray() — The Lazy Converter\n\nSame as np.array() but smarter — if the input is already a NumPy array, \nit does nothing. No copy, no new buffer. Saves memory.\n'

In [67]:
arr_new =  np.asarray(arr) 
arr_new

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
print(np.shares_memory(arr, arr_new))

True


In [ ]:
'''
np.ones() / np.ones_like() — The Ones Filler

Creates an array filled entirely with 1s. 
ones_like copies the shape and dtype of an existing array and fills it with 1s.
'''

In [78]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [80]:
z = np.ones((2, 3,3))*10
z

array([[[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]])

In [83]:
np.ones_like(z)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
'''
np.zeros() / np.zeros_like() — The Zeros Filler

Identical to ones but fills with 0s. 
Most common array initializer in ML — model weights often start at zero.
'''

In [84]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [86]:
np.zeros((3, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [90]:
z

array([[[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]])

In [89]:
np.zeros_like(z, np.int8)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int8)

In [ ]:
'''
np.empty() / np.empty_like() — The Uninitialized Buffer

Allocates memory but does not fill it with anything. 
Whatever random bytes were sitting in that RAM location — that is what you get. 
Fastest creation function because it skips the fill step.
'''

In [97]:
np.empty((2, 2, 4)) # fills with random values

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         1.06811083e-306],
        [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
         9.79107872e-307]],

       [[6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
         1.78021527e-306],
        [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
         1.33512173e-306]]])

In [98]:
np.empty_like(z) # fills with random values 

array([[[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]])

In [ ]:
'''
np.full() / np.full_like() — The Custom Filler

Creates an array filled with any value you specify. Not just 0 or 1 — any number.
'''

In [101]:
np.full(5 ,42) # 1st parameter for dinmention and 2nd to fill desired value

array([42, 42, 42, 42, 42])

In [103]:
np.full( (5,10), 6)

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

In [105]:
np.full( (2, 5,10), 2)

array([[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]])

In [108]:
z

array([[[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]],

       [[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]]])

In [109]:
np.full_like(z, 7, np.int8)

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]], dtype=int8)

In [ ]:
'''
np.eye() / np.identity() — The Identity Matrix

Creates a square matrix with 1s on the diagonal and 0s everywhere else. 
Used in linear algebra — the matrix equivalent of the number 1.
'''

In [112]:
np.eye(3).astype(np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [115]:
np.identity(3, np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [117]:
import numpy as np

In [123]:
# ── PART 1 — Your first array ─────────────────────────────────

python_prices = [500, 1200, 850, 750]
numpy_prices = np.array(python_prices)
print(numpy_prices)
print(type(numpy_prices))

[ 500 1200  850  750]
<class 'numpy.ndarray'>


In [128]:
# ── PART 2 — The metadata contract ───────────────────────────
print(len(numpy_prices))
print(numpy_prices.dtype)
print(numpy_prices.shape)
print(numpy_prices.ndim)
print(numpy_prices.size)
print(numpy_prices.itemsize)
print(numpy_prices.nbytes)

4
int32
(4,)
1
4
4
16


In [133]:
# ── PART 3 — Controlling the dtype ───────────────────────────

# float64 — decimal numbers, 8 bytes each
prices_f64 = np.array(python_prices, np.float64)
print(prices_f64)
print(prices_f64.itemsize)
print(prices_f64.nbytes)

# float32 — less precision, 4 bytes each — used in ML models
prices_f32 = np.array(python_prices, np.float32)
print(prices_f32)
print(prices_f32.itemsize)
print(prices_f32.nbytes)

'''Same values. Half the memory and low precision
1 million rows × 100 features = 800MB in float64
                              = 400MB in float32
This is why dtype choice matters in production.
'''

[ 500. 1200.  850.  750.]
8
32
[ 500. 1200.  850.  750.]
4
16


In [137]:
# ── PART 4 — Creating arrays without typing every number ─────
zeros =  np.zeros(6, np.int8)
ones = np.ones(6, np.int8)
weekdays = np.arange(1, 8)
percentages = np.linspace(0,100, 5)

print(zeros)
print(ones)
print(weekdays)
print(percentages)

[0 0 0 0 0 0]
[1 1 1 1 1 1]
[1 2 3 4 5 6 7]
[  0.  25.  50.  75. 100.]


In [140]:
# ── PART 5 — The operation that makes NumPy worth using ───────
prices = [1000, 900, 1100, 3000, 700]
original_prices = np.array(prices)
sale = .25
sales = original_prices*sale
discounted_prices = original_prices - sales

print(original_prices)
print(discounted_prices)

[1000  900 1100 3000  700]
[ 750.  675.  825. 2250.  525.]


--------------------------------
******** PROJECT ********
--------------------------------

In [ ]:
**The scenario:** You are a data analyst at a company in Lahore. Here is one week of daily website visitors:
```
Monday: 1240  Tuesday: 980   Wednesday: 1560
Thursday: 1100  Friday: 1890  Saturday: 2340  Sunday: 760

In [156]:
visitors = [1240, 980, 1560, 1100, 1890, 2340, 760]

Create a NumPy array from this data. Print all six metadata values: dtype, shape, ndim, size, itemsize, nbytes.

In [157]:
weekly_visitors = np.array(visitors)
print(f'Weekly Visitors: {weekly_visitors}')
print(f'Data Type: {weekly_visitors.dtype} ')
print(f'Shape: {weekly_visitors.shape}')
print(f'Dimensions: {weekly_visitors.ndim}')
print(f'Size: {weekly_visitors.size}')
print(f'Size per Item: {weekly_visitors.itemsize}' )
print(f'Total Bytes: {weekly_visitors.nbytes}')

Weekly Visitors: [1240  980 1560 1100 1890 2340  760]
Data Type: int32 
Shape: (7,)
Dimensions: 1
Size: 7
Size per Item: 4
Total Bytes: 28


Task 2 — Summary statistics, one line each

Using your visitors array, find and print:

Total visitors for the week

Average daily visitors

Highest single day

Lowest single day

Difference between highest and lowest

In [163]:
print(f'Total visitors for the week: {weekly_visitors.sum()}')
print(f'Average Daily Visitors: {weekly_visitors.mean()}')
print(f'Highest single day visitor: {weekly_visitors.max()}')
print(f'Lowest single day visitor: {weekly_visitors.min()}')
print(f'Difference between highest and lowest: {weekly_visitors.max() - weekly_visitors.min()}')

Total visitors for the week: 9870
Average Daily Visitors: 1410.0
Highest single day visitor: 2340
Lowest single day visitor: 760
Difference between highest and lowest: 1580


Task 3 — dtype experiment

Create two new arrays from the same visitor data:

One with dtype=np.float32

One with dtype=np.int16

In [165]:
weekly_visitors_f32 = weekly_visitors.astype(np.float32)
weekly_visitors_i16 = weekly_visitors.astype(np.int16)

print(weekly_visitors_f32)
print(weekly_visitors_i16)

[1240.  980. 1560. 1100. 1890. 2340.  760.]
[1240  980 1560 1100 1890 2340  760]


Your manager wants projected visitor numbers if the site grows 10% per month for 6 months. 
Start from your weekly average in Task 2.

In [171]:
weekly_visitor_avg = weekly_visitors.mean() 
months = np.arange(1, 7)
projection = np.round( weekly_visitor_avg * (1.10 ** months) ).astype(int)
print(projection)

[1551 1706 1877 2064 2271 2498]
