# Practice

### Linear Algebra

In [2]:
import numpy as np

In [47]:
x = np.arange(1,7).reshape(2,3).astype('f8')
y = np.array([ [6., 23.], [-1, 7], [8,9] ])
print(x,'\n\n', y)

'''
Mental Note:
x: (2,3) -> (row1, col1)
y: (3,2) -> (row2, col2)

iff size(col1) == size(row2), perform dot product i.e., x.dot(y)
otherwise shape not aligned error

Result shape( x.dot(y) ): (row1, col2)
'''
np.dot(x,y)

[[1. 2. 3.]
 [4. 5. 6.]] 

 [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


array([[ 28.,  64.],
       [ 67., 181.]])

In [32]:
a = np.arange(1, 100001).reshape(5,20000)
b = np.arange(100001,200001).reshape(20000,5)

%timeit a.dot(b)
%timeit np.dot(a, b)

384 μs ± 44.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
410 μs ± 50.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [48]:
b = np.ones(3)

'''
x:          (2,3) -> (row1, col1)
np.ones(3): (3,) -> (row2, col2)

When multiplying a Matrix (2D) by a Vector (1D):
1. If the vector is on the right: Its size must match the columns of the matrix.
        (m, n) × (n,) -> (m,)

2.If the vector is on the left: Its size must match the rows of the matrix.
        (m,) × (m, n) -> (n,)

'''

print(f'x: \n{x} \n\nb: \n{b} \n\n{ x @ b}') 

x: 
[[1. 2. 3.]
 [4. 5. 6.]] 

b: 
[1. 1. 1.] 

[ 6. 15.]


In [69]:
from numpy.linalg import inv, qr
np.random.seed(42)
x = np.random.randint(1, 11, size = (5, 5))
trans = x.T
mat = x.T @ x

print(f'''
 x: \n{x}
\n Transpose of x: \n{trans}
\n mat: \n{mat}
\n Inverse of mat: \n{inv(mat)}
''')



 x: 
[[ 7  4  8  5  7]
 [10  3  7  8  5]
 [ 4  8  8  3  6]
 [ 5  2  8  6  2]
 [ 5  1 10  6  9]]

 Transpose of x: 
[[ 7 10  4  5  5]
 [ 4  3  8  2  1]
 [ 8  7  8  8 10]
 [ 5  8  3  6  6]
 [ 7  5  6  2  9]]

 mat: 
[[215 105 248 187 178]
 [105  94 143  86 104]
 [248 143 341 228 245]
 [187  86 228 170 159]
 [178 104 245 159 195]]

 Inverse of mat: 
[[ 0.73862716 -0.33601317  0.55853169 -1.14696955 -0.26155062]
 [-0.33601317  0.1877487  -0.28394623  0.54162743  0.12170535]
 [ 0.55853169 -0.28394623  0.52236598 -0.93639287 -0.25118683]
 [-1.14696955  0.54162743 -0.93639287  1.85357915  0.42322305]
 [-0.26155062  0.12170535 -0.25118683  0.42322305  0.1494716 ]]



In [70]:
import numpy as np

# A transformation that scales and rotates
A = np.array([[0, -1], 
              [1,  0]]) 

# The "Undo" button
A_inv = np.linalg.inv(A)

# Apply A, then A_inv. Result should be the Identity matrix:
# [[1, 0]
#  [0, 1]]
print(A @ A_inv)

[[1. 0.]
 [0. 1.]]


#### Resourse and Impact:
Resource link: https://www.youtube.com/watch?v=XkY2DOUCWMU&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=4
##### Impact: 
###### I am using rewired thinking from the video. I will trying to use the mental notes what I have learnt and think in term of linear algebra.

#### Mental Notes:

1. np.diag(A): Extracts the diagonal elements [4, 3] from A. Use for square matrix only.

2. np.trace(A): Adds diagonal elements ($4 + 3 = 7$). Use for square matrix only.

3. np.linalg.det(A): The Determinant. It tells you the factor by which area/volume changes. If det is $10$, the area of a single grid square is now $10\times$ larger. If it is $0$, your space is squashed flat.  Use for square matrix only.

4. np.linalg.inv(A): Only works if the matrix is square and not squashed (det != 0).

5. np.linalg.solve(A, b): Finds the exact $\vec{x}$ for $A\vec{x} = b$. Fast and stable

In [146]:
A = np.array([
    [4, 2],
    [1, 3]
]) # 2D Transfor,ation matrix (A)

b = np.array([10, 5]) # 1D vector

C = np.array ([
    [1, 2],
    [3, 4],
    [5, 6]
]) 

print(f'''
extract diagonal element of A: { np.diag(A) }
add diagnoal elements of A: { np.trace(A) }
the determinent of A: { np.round( np.linalg.det(A) ) }

inverse of A:  \n{ np.linalg.inv(A) }

to find the value of x
Ax = b: {np.linalg.solve(A, b)}
Ax = A: \n{np.linalg.solve(A, A)}
''')


extract diagonal element of A: [4 3]
add diagnoal elements of A: 7
the determinent of A: 10.0

inverse of A:  
[[ 0.3 -0.2]
 [-0.1  0.4]]

to find the value of x
Ax = b: [2. 1.]
Ax = A: 
[[1. 0.]
 [0. 1.]]



#### Pseudorandom Number Generation

### Mental Note

###### rng.permutation (The Re-Arranger): 
It takes an existing array and returns a copy with the elements in a random order. It’s like shuffling a deck of cards.

##### rng.choice (The Sub-Sampler):  
It picks $N$ elements from a list. You can decide if you want to allow picking the same item twice (replace=True) or not (replace=False).

##### rng.integers (The Discrete Grid): 
It generates whole numbers within a specific range [low, high).

#### rng.standard_normal vs. rng.normal
These both deal with the Bell Curve (Gaussian Distribution), which is the \'Natural Law\' of data. Most errors, measurements, and physical traits follow this shape.

##### rng.standard_normal (The "Pure" Bell Curve)The Rule: 
The Mean ($\mu$) is always 0 and the Standard Deviation ($\sigma$) is always 1.Usage: It's the "raw" version. Engineers use it to generate "unit noise."

##### rng.normal (The "Custom" Bell Curve)The Rule: 
You define the Center (loc/mean) and the Spread (scale/std dev).Usage: Simulating real things. If you want to simulate "Human Heights," you don't start at 0. You start at 170cm with a spread of 10cm.

In [76]:
rng = np.random.default_rng(seed=42)
data = rng.standard_normal((12,3))
data

array([[ 0.30471708, -1.03998411,  0.7504512 ],
       [ 0.94056472, -1.95103519, -1.30217951],
       [ 0.1278404 , -0.31624259, -0.01680116],
       [-0.85304393,  0.87939797,  0.77779194],
       [ 0.0660307 ,  1.12724121,  0.46750934],
       [-0.85929246,  0.36875078, -0.9588826 ],
       [ 0.8784503 , -0.04992591, -0.18486236],
       [-0.68092954,  1.22254134, -0.15452948],
       [-0.42832782, -0.35213355,  0.53230919],
       [ 0.36544406,  0.41273261,  0.430821  ],
       [ 2.1416476 , -0.40641502, -0.51224273],
       [-0.81377273,  0.61597942,  1.12897229]])

In [90]:
# 1000 samples of "Height" (Normal distribution: mean 170cm, std 10)
heights = rng.normal(170, 10, size=1000)
heights[:10]

array([155.63030703, 183.70283118, 160.08755688, 164.35660881,
       175.61392444, 182.33220166, 158.46423368, 164.87455122,
       170.97532073, 168.13633995])

In [93]:
user_ids = rng.integers(1, 11, 10) # generate random numbers, range [1, 110).
user_ids

array([ 8,  5,  8, 10,  7,  2,  4,  2,  4,  9], dtype=int64)

In [98]:
cities = ['Lahore', 'Karachi', 'Islamabad', 'Peshawar']
sample = rng.choice(cities)
print( sample )

sample_1 = rng.choice(cities, size=5, replace=True) # Randomly select 5 cities for a marketing survey

print(f"Survey Cities: {sample_1}")

shuffled_data = rng.permutation(cities)
print(f"Shuffled for Training: {shuffled_data}")

Peshawar
Survey Cities: ['Lahore' 'Karachi' 'Islamabad' 'Karachi' 'Islamabad']
Shuffled for Training: ['Lahore' 'Peshawar' 'Karachi' 'Islamabad']


# Task

In [49]:
import numpy as np
import time

#### ── PART 1 — Dot product & matrix multiply ────

In [177]:
a = np.array([1,2,3], 'f8')
b = np.array([4,5,6], 'f8')
dot = np.dot(a, b)
print(f'{dot}, {dot.dtype}, {dot.shape} \n{a @ b} \n') 


A = np.array([ [1, 2], [3, 4], [5, 6] ], 'f8')
B = np.array([ [1, 0, 1], [0, 1, 0] ], 'f8')

C = A@B
print(f'\tA @ B: {A.shape} @ {B.shape} = {C.shape} \n{C}')

rng = np.random.default_rng(42)

X = rng.standard_normal((100, 5))
w = rng.standard_normal(5)

predictions = X @ w

print(f'\n\nX: {X.shape} w: {w.shape} \nX.w: {predictions.shape} ')

32.0, float64, () 
32.0 

	A @ B: (3, 2) @ (2, 3) = (3, 3) 
[[1. 2. 1.]
 [3. 4. 3.]
 [5. 6. 5.]]


X: (100, 5) w: (5,) 
X.w: (100,) 


#### ── PART 2 — Essential linear algebra operations ───

In [43]:
A= np.arange(1,7).reshape((2,3)).astype('f8')
print(f'A: {A.shape} \nA^T: {A.T.shape}')

B = square = np.arange(1,5).reshape((2,2)).astype('f8') # determinent is always of quare matrix
det = np.linalg.det(B)
print( '\ndet(B):', np.round(det) )

inv_B = np.linalg.inv(B) # inverse of original matrix's shape remains same
print(f'''
B: {B.shape} \n{B} \n\nB^-1: {inv_B.shape} \n{inv_B} 

B @ B^-1: \n{ np.round(B @ inv_B) }
''')


sys = np.array([ [4,2], [2,3]], 'f8')
eig_val, eig_vec = np.linalg.eig(sys)
print(f'''
\tEigen Values: \n{eig_val}
\n\tEigen Vectors: \n{eig_vec}
''')

A: (2, 3) 
A^T: (3, 2)

det(B): -2.0

B: (2, 2) 
[[1. 2.]
 [3. 4.]] 

B^-1: (2, 2) 
[[-2.   1. ]
 [ 1.5 -0.5]] 

B @ B^-1: 
[[1. 0.]
 [0. 1.]]


	Eigen Values: 
[5.56155281 1.43844719]

	Eigen Vectors: 
[[ 0.78820544 -0.61541221]
 [ 0.61541221  0.78820544]]



#### ── PART 3 — Solving a real linear system ────

In [47]:
A = np.array([ [3,1], [1,2] ], 'f8')
b = np.array([9,8], 'f8')

x = np.linalg.solve(A, b)  # Never do this — slow and unstable: x = np.linalg.inv(A) @ b
print(f'Ax = b -> x = inv(A).b: {x}')
print(np.allclose(A @ x, b)) 

Ax = b -> x = inv(A).b: [2. 3.]
True


##### np.allclose(A @ x, b)
1. A @ x: It takes your starting vector $x$ and applies the transformation $A$ to see where it lands.
2. Comparison: It compares that landing spot to your target $b$, element by element.
3. Tolerance: It checks if the difference is smaller than a very tiny threshold (by default, $1 \times 10^{-8}$).
4. The Result: It returns True if every single element is "close enough," and False if even one element is significantly off.

#### ── PART 4 — Performance profiling ──────

##### %timeit — best for single operations in Jupyter 
Runs multiple times and reports mean ± std dev

##### time.perf_counter — best for larger blocks of code

In [60]:
rng = np.random.default_rng(42)
X = rng.standard_normal((10_000, 100)) # equivalent to 'np.random.randn(10000, 100)'
w = rng.standard_normal(100)

def predict_loop(X, w):
    results = []
    for row in X:
        results.append( np.dot(row, w) )
    return np.array(results)

def predict_matmul(X,w):
    return X @ w

def predict_einsum(X, w):
    return np.einsum('ij,j->i', X, w)

# Time all three
start = time.perf_counter()
r1 = predict_loop(X, w)
t1 = time.perf_counter() - start

start = time.perf_counter()
r2 = predict_matmul(X, w)
t2 = time.perf_counter() - start

start = time.perf_counter()
r3 = predict_einsum(X, w)
t3 = time.perf_counter() - start

print(f"Loop:    {t1:.4f}s")
print(f"Matmul:  {t2:.6f}s")
print(f"Einsum:  {t3:.6f}s")
print(f"Matmul speedup: {t1/t2:.0f}x")

# Verify all give same result
print(np.allclose(r1, r2)) 
print(np.allclose(r1, r3))

Loop:    0.0216s
Matmul:  0.004283s
Einsum:  0.002802s
Matmul speedup: 5x
True
True


#### ── PART 5 — Memory profiling ────

In [78]:
A = rng.standard_normal((1000, 1000), 'f8')
print(f' A: {A.nbytes/ 1e06:.1f} MB') # '1e06' == 1_000_000, ':.1f' == upto 1 decimal point
print(f' A.T: {A.T.nbytes / 1e6:.1f} MB ')

B = A.copy()
print(f' A.copy(): {A.copy().nbytes/1e06:.2f}, view? {np.shares_memory(A, B)} ')

C = A @ A.T
print(f''' A @ A.T: {C.nbytes/1e06:.1f} MB, view? {np.shares_memory(C,A)}

Total in RAM: {(A.nbytes + B.nbytes + C.nbytes)/1e6:.3f} MB

''')


 A: 8.0 MB
 A.T: 8.0 MB 
 A.copy(): 8.00, view? False 
 A @ A.T: 8.0 MB, view? False

Total in RAM: 24.000 MB




# Project

In [149]:
import numpy as np
import time

In [150]:
rng = np.random.default_rng(42)

n_samples = 1000 # Simulated housing data — Lahore property market
n_features = 5 # Features: size_sqft, bedrooms, age_years, distance_from_centre_km, floor_number

x_raw = rng.standard_normal((n_samples, n_features)).astype('f8')
true_weights = np.array([150.0, 50.0, -20.0, -30.0, 10.0])
noise = rng.standard_normal(n_samples) * 10
y = x_raw @ true_weights + noise

#### Task 1 — Feature matrix engineering

In [166]:
print(x_raw.shape, y.shape)
'''
x_raw is 1000 records each with 5 features: (1000, 5)
y: transformed records: (1000,)

'''
bias = np.ones((n_samples, 1))
x = np.hstack([bias, x_raw]) #horizontal stack
print(f'''
x  shape: {x.shape}, 
    dtype: {x.dtype} 
    view? {np.shares_memory(x, x_raw)}
    memory: {x.nbytes:.0f} bytes
    
x_raw memory: {x.nbytes:.0f} bytes

''')

mean =  x_raw.mean(axis=0)
std = np.std(x_raw, axis = 0)
x_normalize = (x_raw - mean)/std
print(f'''
Normalized: \n{x_normalize}

Mean: \n{x_normalize.mean(0)}

Standard Deviation: \n{x_normalize.std(0)}
''')

x_final = np.hstack([bias, x_normalize])

(1000, 5) (1000,)

x  shape: (1000, 6), 
    dtype: float64 
    view? False
    memory: 48000 bytes
    
x_raw memory: 48000 bytes



Normalized: 
[[ 0.35039293 -1.01331246  0.77292994  0.94759894 -1.96202524]
 [-1.25649025  0.11462441 -0.33029351  0.00747339 -0.83380964]
 [ 0.92506903  0.74237652  0.06507099  1.13091374  0.52309442]
 ...
 [ 0.46517216  0.36779113  0.28185518 -0.46169851  0.89274036]
 [-1.51467606 -0.07242991 -0.58640592 -0.64112912  0.48326588]
 [ 1.12314794 -0.34038122  0.80419508  0.07281692 -0.87459042]]

Mean: 
[ 2.44249065e-18  1.14352972e-17 -1.15463195e-17 -1.41969769e-17
 -2.87547763e-17]

Standard Deviation: 
[1. 1. 1. 1. 1.]



#### Task 2 — The normal equation (closed-form linear regression)

In [173]:
x = x_final
left_side = x.T @ x # (6, 1000) * (1000, 6) -> (6,6)
right_side = x.T @ y # # (6, 1000) * (1000) -> (6,)
print(f'''
Left side: {left_side.shape}
Right side: {right_side.shape}
{left_weight.shape == right_weight.shape}
''')

# The system to solve: (X.T @ X) @ w = X.T @ y
learned_weights = np.linalg.solve(left_side, right_side)

print(f'''{np.allclose(true_weights, learned_weights[1:])}
Learned Weights: {np.round( learned_weights[1:], 1)}
True Weights:  {true_weights}
''')

np.linalg.cond(left_side) # 1.2620122638816995 < 1e10(10_000_000_000)


Left side: (6, 6)
Right side: (6,)
False

False
Learned Weights: [149.5  51.6 -19.4 -30.6   9.6]
True Weights:  [150.  50. -20. -30.  10.]



1.1971392501356317

#### Task 3 — Performance audit of the full pipeline

In [162]:
w = learned_weights
def predict_v1(x, w):
    results = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        results[i] = np.dot(x[i],w)
    return results

def predict_v2(x, w):      #prefered version in production cus its build in for c using numpy
    return np.dot(x, w)

def predict_v3(x,w):
    return (x*w).sum(axis = 1)


start = time.perf_counter()
results_v1 = predict_v1(x, w)
t1 = time.perf_counter() -start

start = time.perf_counter()
results_v2 = predict_v2(x,w)
t2 = time.perf_counter() - start

start = time.perf_counter()
results_v3 = predict_v3(x, w)
t3 = time.perf_counter() - start

print(f'''
v1 vs v2: {np.allclose( results_v1, results_v2)}
v1 vs v3: {np.allclose( results_v1, results_v3)}
v2 vs v3: {np.allclose( results_v2, results_v3)}


v1  shape:  {results_v1.shape}
    memory: {results_v1.nbytes:.0f} bytes
    
v2  shape:  {results_v2.shape}
    memory: {results_v2.nbytes:.0f} bytes

v3  shape:  {results_v3.shape}
    memory: {results_v3.nbytes:.0f} bytes
''')



v1 vs v2: True
v1 vs v3: True
v2 vs v3: True


v1  shape:  (1000,)
    memory: 8000 bytes
    
v2  shape:  (1000,)
    memory: 8000 bytes

v3  shape:  (1000,)
    memory: 8000 bytes

