# Practice

## Universal Functions: Fast Element-Wise Array Functions

### SneakPeak

In [32]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
%timeit compute_reciprocals(values)
 

12.5 μs ± 624 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.31 s ± 64.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%timeit (1.0 / big_array)

3.5 ms ± 381 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Intro to UFuncs

##### A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. 
###### You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [65]:
print( arr.min() )
print( np.min(arr) )

print( arr.max() )
print( np.max(arr) )

print( arr.sum() )
print( np.add(arr, arr) )

0
0
9
9
45
[ 0  2  4  6  8 10 12 14 16 18]


In [64]:
rng = np.random.default_rng(seed=0)
x = rng.standard_normal(8)
y = rng.standard_normal(8)
print(f'''x: {x}
\t\t------
y: {y} 
\t\t------
max(x, y): {np.maximum(x, y)} ''') # np.maximum will compare both arrays in pair and take max value as final

x: [ 0.12573022 -0.13210486  0.64042265  0.10490012 -0.53566937  0.36159505
  1.30400005  0.94708096]
		------
y: [-0.70373524 -1.26542147 -0.62327446  0.04132598 -2.32503077 -0.21879166
 -1.24591095 -0.73226735] 
		------
max(x, y): [ 0.12573022 -0.13210486  0.64042265  0.10490012 -0.53566937  0.36159505
  1.30400005  0.94708096] 


In [76]:
arr = rng.standard_normal(7)*5
arr

array([-5.92058983, -3.30851286, -2.18217624, -5.84900954,  8.69683939,
       -2.47955364,  1.64484815])

In [77]:
remainder, whole_part = np.modf(arr)
print(remainder, whole_part)

[-0.92058983 -0.30851286 -0.18217624 -0.84900954  0.69683939 -0.47955364
  0.64484815] [-5. -3. -2. -5.  8. -2.  1.]


In [89]:
print(arr)
in_out = np.zeros_like(arr)
np.add(arr, 1)

[-5.92058983 -3.30851286 -2.18217624 -5.84900954  8.69683939 -2.47955364
  1.64484815]


array([-4.92058983, -2.30851286, -1.18217624, -4.84900954,  9.69683939,
       -1.47955364,  2.64484815])

In [92]:
np.add(arr, 1, out=in_out) #out is gonna write directly to in_out rather than creating new array
in_out

array([-4.92058983, -2.30851286, -1.18217624, -4.84900954,  9.69683939,
       -1.47955364,  2.64484815])

# Important UFunc Section

##### := is called the walrus operator. It assigns a value AND returns it in the same expression.

In [157]:
arr1a = np.arange(1,11)
arr2a = np.arange (11,21)
arr3a = np.array([-3.1,  1, -2, 6.9, -7])
print(f'''
 Add: \n{np.add(arr2a, arr1a)}, \n{arr2a+arr1a}
\n Substract: \n{np.subtract(arr2a, arr1a)}, \n{arr2a-arr1a}
\n Multiply: \n{np.multiply(arr2a, arr1a)}, \n{arr2a*arr1a}
\n Divide: \n{np.divide(arr2a, arr1a)}, \n{arr2a/arr1a}
\n Floor: \n{np.floor_divide(arr2a, arr1a)}, \n{arr2a//arr1a}
\n Power: \n{np.power(arr2a, arr1a)}, \n{arr2a**arr1a}
\n Module: \n{np.mod(arr2a, arr1a)}, \n{arr2a%arr1a}
-------------------------------------------------------
np.negative flips the sign of every element. 
Positive becomes negative. Negative becomes positive.
-------------------------------------------------------
\n Negative: \n{np.negative(arr1a)}, { np.negative(arr1a) == -arr1a }

{np.negative(arr2a)}, { np.negative(arr2a) == -arr2a }
{np.negative(arr3a)}
\n Absolute: {np.abs(-arr2a)}, {np.abs(-arr1a)}, {np.abs(arr3a)}
\n Round: {np.rint(arr3a)}, {np.round(arr3a)}, { np.rint(arr3a) == np.round(arr3a) }
\n Round: { (a:= np.rint(arr3a) )}, { (b:= np.round(arr3a) )}, { a == b } #observe the behaviour of a:= and b:= here
\n Sign: {np.sign(arr3a)}
\n Floor: {np.floor(arr3a)}
\n Ceiling: {np.ceil(arr3a)}


\n Square: {np.square(arr1a)}, {np.square(arr2a)}
\n Square Root: {np.sqrt(arr1a)}, {np.sqrt(arr2a)}
\n Exponet: e raised to each element \n\n{np.exp(arr1a)}, \n\n{np.exp(arr3a)}
''')



 Add: 
[12 14 16 18 20 22 24 26 28 30], 
[12 14 16 18 20 22 24 26 28 30]

 Substract: 
[10 10 10 10 10 10 10 10 10 10], 
[10 10 10 10 10 10 10 10 10 10]

 Multiply: 
[ 11  24  39  56  75  96 119 144 171 200], 
[ 11  24  39  56  75  96 119 144 171 200]

 Divide: 
[11.          6.          4.33333333  3.5         3.          2.66666667
  2.42857143  2.25        2.11111111  2.        ], 
[11.          6.          4.33333333  3.5         3.          2.66666667
  2.42857143  2.25        2.11111111  2.        ]

 Floor: 
[11  6  4  3  3  2  2  2  2  2], 
[11  6  4  3  3  2  2  2  2  2]

 Power: 
[         11         144        2197       38416      759375    16777216
   410338673 -1864941312   565150579   797966336], 
[         11         144        2197       38416      759375    16777216
   410338673 -1864941312   565150579   797966336]

 Module: 
[0 0 1 2 0 4 3 2 1 0], 
[0 0 1 2 0 4 3 2 1 0]
-------------------------------------------------------
np.negative flips the sign of every eleme

In [161]:
values = np.array([-2.7, -2.2, 2.2, 2.7])

print("floor: ", np.floor(values)) #floor

print("ceil:  ", np.ceil(values)) #ceiling

print("trunc: ", np.trunc(values)) #truncate decimal point to zero

print("rint:  ", np.rint(values)) #round to nearest value

floor:  [-3. -3.  2.  2.]
ceil:   [-2. -2.  3.  3.]
trunc:  [-2. -2.  2.  2.]
rint:   [-3. -2.  2.  3.]


In [160]:
arr2 = np.array([-3.7, 0.0, 1.5, np.nan, np.inf, -np.inf])
print('Absolute:', np.abs(arr2) )
print('NaN:', np.isnan(arr2) )
print('Infinite:', np.isinf(arr2) )
print('Finite:', np.isfinite(arr2) )
print( np.log1p(np.abs(arr2)) )

Absolute: [3.7 0.  1.5 nan inf inf]
NaN: [False False False  True False False]
Infinite: [False False False False  True  True]
Finite: [ True  True  True False False False]
[1.54756251 0.         0.91629073        nan        inf        inf]


### Trignometry

In [187]:
angles = np.array( [0, 45, 90, 135, 180, 225, 270, 315, 360] )
radians = np.deg2rad(angles) # Numpy process trig function in radinas

print(f'''
 Angles = {angles}
\n Radians: {radians}
\n Sin: \n{( a:= np.sin(radians) )}
\n Sin Inverse: \n{np.arcsin(a)}
\n Cos: \n{( b:= np.cos(radians) )}
\n: Cos Inverse: \n{np.arccos(b)}
\n Tan: \n{( c:= np.tan(radians) )}
\n Tan Inverse: \n{np.arctan(c)}
''')

# tan(90°) = mathematically undefined (infinity) but NumPy returns a very large number in float64


 Angles = [  0  45  90 135 180 225 270 315 360]

 Radians: [0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]

 Sin: 
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]

 Sin Inverse: 
[ 0.00000000e+00  7.85398163e-01  1.57079633e+00  7.85398163e-01
  1.22464680e-16 -7.85398163e-01 -1.57079633e+00 -7.85398163e-01
 -2.44929360e-16]

 Cos: 
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00 -7.07106781e-01 -1.83697020e-16  7.07106781e-01
  1.00000000e+00]

: Cos Inverse: 
[0.         0.78539816 1.57079633 2.35619449 3.14159265 2.35619449
 1.57079633 0.78539816 0.        ]

 Tan: 
[ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16  1.00000000e+00  5.44374645e+15 -1.00000000e+00
 -2.44929360e-16]

 Tan Inverse: 
[ 0.00000000e+00  7.85398163e-01  1.57079633e+00 -7.85398163e-01
 -1.22

In [188]:
rad_f64 = np.deg2rad(angles) 
sin_vals = np.sin(rad_f64)
back_to_radians = np.arcsin(sin_vals)

print("Original radians: ", rad_f64)
print("After sin→arcsin: ", back_to_radians)


Original radians:  [0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
After sin→arcsin:  [ 0.00000000e+00  7.85398163e-01  1.57079633e+00  7.85398163e-01
  1.22464680e-16 -7.85398163e-01 -1.57079633e+00 -7.85398163e-01
 -2.44929360e-16]


### Exponents and logarithms

In [197]:
x = [1, 2, 3]
print(f'''
x: {x}
e^x: {np.exp(x)}
2^x: {np.exp2(x)}
3^x: {np.power(3,x)}
''')

# log: inverse of exponents 
print(f'''
natural logarithm - ln(x):    {np.log(x)}
base-2 logarithm  - log2(x):  {np.log2(x)}
base-10 logarithm - log10(x): {np.log10(x)}
''')


x: [1, 2, 3]
e^x: [ 2.71828183  7.3890561  20.08553692]
2^x: [2. 4. 8.]
3^x: [ 3  9 27]


natural logarithm - ln(x):    [0.         0.69314718 1.09861229]
base-2 logarithm  - log2(x):  [0.        1.        1.5849625]
base-10 logarithm - log10(x): [0.         0.30103    0.47712125]



#### Aggregates

In [275]:
x = np.arange(1, 6)
print(f'''
x: {x}

Calling reduce on the add ufunc returns the sum of all elements in the array
{np.add.reduce(x)}

Calling reduce on the multiply ufunc results in the product of all array elements
{np.multiply.reduce(x)}

{np.subtract.reduce(x)}

{np.add.accumulate(x)}
{np.cumsum(x) }
{ np.add.accumulate(x) == np.cumsum(x) }

Outer Product: \n{np.multiply.outer(x, x)}
''')


x: [1 2 3 4 5]

Calling reduce on the add ufunc returns the sum of all elements in the array
15

Calling reduce on the multiply ufunc results in the product of all array elements
120

-13

[ 1  3  6 10 15]
[ 1  3  6 10 15]
[ True  True  True  True  True]

Outer Product: 
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]



### Aggregations

In [243]:
import random
np.random.seed(0)
L = np.random.random(100)
print(f'''
{L}
Sum: a) {L.sum()} b) {sum(L)}
\t{ L.sum() == sum(L) }
''')


[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918
 0.11827443 0.63992102 0.14335329 0.94466892 0.52184832 0.41466194
 0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
 0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195
 0.6976312  0.06022547 0.66676672 0.67063787 0.21038256 0.1289263
 0.31542835 0.36371077 0.57019677 0.43860151 0.98837384 0.10204481
 0.20887676 0.16130952 0.65310833 0.2532916  0.46631077 0.24442559
 0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517
 0.82099323 0.09710128 0.83794491 0.09609841 0.97645947 0.4686512
 0.97676109 0.60484552 0.73926358 0.03918779 0.28280696 0.12019656
 0.2961402  0.11872772 0.31798318 0.41426299 0.0641475  0.69247212
 0.56660145 0.26538949 0.52324805 0.09394051 0.5759465  0.929296

In [244]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

97 ms ± 8.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
696 μs ± 71.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [246]:
%timeit min(big_array), max(big_array)
%timeit np.min(big_array), np.max(big_array)

98.3 ms ± 11.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
581 μs ± 58.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [263]:
M = np.random.random((3, 4))
print(f'''
 M: {M}
\n Sum: {M.sum()}

 Max(axis 0): {M.max(axis=0)}
 Max(axis 1): {M.max(axis=1)}
\n Max: {M.max()}

 Min(axis 0): {M.min(axis=0)}
 Min(axis 1): {M.min(axis=1)}
\n Min: {M.min()}

''')


 M: [[0.01943519 0.35224155 0.1675703  0.51614172]
 [0.58497777 0.69151272 0.10767919 0.68685106]
 [0.36899511 0.96998923 0.34613552 0.86073407]]

 Sum: 5.672263424715273

 Max(axis 0): [0.58497777 0.96998923 0.34613552 0.86073407]
 Max(axis 1): [0.51614172 0.69151272 0.96998923]

 Max: 0.9699892312869823

 Min(axis 0): [0.01943519 0.35224155 0.10767919 0.51614172]
 Min(axis 1): [0.01943519 0.10767919 0.34613552]

 Min: 0.019435190864985685




# Task

In [276]:
import numpy as np
import time

#### ── PART 1 — What ufuncs actually are ───────

In [293]:
arr = np.arange(1, 6, dtype= np.float64)
print(f'''
{arr}
\n{np.square(arr)}
\n{np.sqrt(arr)}
\n{( a:= np.exp(arr))}
\n{np.log(a)}
''')
np.abs([-1, -2, -3, -4, -5])


[1. 2. 3. 4. 5.]

[ 1.  4.  9. 16. 25.]

[1.         1.41421356 1.73205081 2.         2.23606798]

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

[1. 2. 3. 4. 5.]



array([1, 2, 3, 4, 5])

#### ── PART 2 — Binary ufuncs (two arrays) ────

In [298]:
a = np.array([1, 4, 9, 16, 25], 'f8')
b = np.array([1, 2, 3, 4, 5], 'f8')
print(f'''
{( b:= np.add(b, a) ), b.dtype}
{ np.subtract(b, a) }
{ np.multiply(b, a) }
{ np.divide(b, a) }
{ np.power(b, a) }
{ np.maximum(a,b) }
{ np.minimum(a, b) }
''')



(array([ 2.,  6., 12., 20., 30.]), dtype('float64'))
[1. 2. 3. 4. 5.]
[  2.  24. 108. 320. 750.]
[2.         1.5        1.33333333 1.25       1.2       ]
[2.00000000e+00 1.29600000e+03 5.15978035e+09 6.55360000e+20
 8.47288609e+36]
[ 2.  6. 12. 20. 30.]
[ 1.  4.  9. 16. 25.]



#### ── PART 3 — Aggregations, the axis concept ─────

In [330]:
sales = np.array([
    [1000, 1500, 1200],   # Row 0 — Product A: North, Central, South
    [2000, 2500, 1800],   # Row 1 — Product B: North, Central, South
    [1500, 1000, 2200],   # Row 2 — Product C: North, Central, South
])

print(f'''
Sum: \t{sales.sum()}
Per Region:: {( a:= sales.sum(axis=0) )}, {a.shape} \'total per region\'
Per Product: {( b:= sales.sum(axis=1) )}, {b.shape} \'total per product\'

Region-wise 

max : { sales.max(axis=0) }
min : { sales.min(axis=0) }
avg: { sales.mean(axis=0) }

Product-wise

max : { sales.max(axis=1) }
min : { sales.min(axis=1) }
avg: { sales.mean(axis=1) }

Overall
max : { np.max(sales) }
min : { np.min(sales) }
avg: { np.mean(sales) }
''')


Sum: 	14700
Per Region:: [4500 5000 5200], (3,) 'total per region'
Per Product: [3700 6300 4700], (3,) 'total per product'

Region-wise 

max : [2000 2500 2200]
min : [1000 1000 1200]
avg: [1500.         1666.66666667 1733.33333333]

Product-wise

max : [1500 2500 2200]
min : [1000 1800 1000]
avg: [1233.33333333 2100.         1566.66666667]

Overall
max : 2500
min : 1000
avg: 1633.3333333333333



In [321]:
%timeit sales.sum()
%timeit np.sum(sales)

'''
sales.sum():
  array.sum() → C function → result

np.sum(sales):
  np.sum() → type check → dispatch → array.sum() → C function → result
  ↑ extra steps here
-----------------------------------------------------------------------

Tip:

arr.sum()     → use this in performance-critical code
               tight loops, inference pipelines

np.sum(arr)   → use this when input type is uncertain
               might be a list, might be an array
               np.sum handles both gracefully
'''

2.66 μs ± 347 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
4.97 μs ± 674 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### ── PART 4 — Performance: proving it with numbers ────

In [336]:
np.random.seed(20)
big_arr = np.random.randn(1_000_000)

# METHOD 1 — Python loop
def sum_loop(arr):
    total = 0.0
    for x in arr:
        total += x
    return total

# METHOD 2 — NumPy ufunc
def sum_numpy(arr):
    return np.sum(arr)

# Time them properly
start = time.perf_counter()
result_loop = sum_loop(big_arr)
time_loop = time.perf_counter() - start

start = time.perf_counter()
result_numpy = sum_numpy(big_arr)
time_numpy = time.perf_counter() - start

print(f"Loop result:  {result_loop:.4f}")
print(f"NumPy result: {result_numpy:.4f}")
print(f"Loop time:    {time_loop:.4f}s")
print(f"NumPy time:   {time_numpy:.6f}s")
print(f"Speedup:      {time_loop/time_numpy:.0f}x faster")

Loop result:  1440.7053
NumPy result: 1440.7053
Loop time:    0.1363s
NumPy time:   0.001593s
Speedup:      86x faster


# Project

In [393]:
import numpy as np

np.random.seed(42)

data = np.random.randint(1, 100, size=(5, 4, 3)).astype(np.float64)

data[:, :, 0] = data[:, :, 0] * 0.5      # delivery time: 0.5–50 hours
data[:, :, 1] = data[:, :, 1] * 1000     # cost: 1000–100000 PKR
data[:, :, 2] = (data[:, :, 2] / 10)     # rating: 0.1–10.0

cities  = ['Lahore', 'Karachi', 'Islamabad', 'Peshawar', 'Quetta']
weeks   = ['Week1', 'Week2', 'Week3', 'Week4']
metrics = ['Delivery_Time', 'Cost_PKR', 'Rating']

'''
data.shape = (5, 4, 3)
              ↑  ↑  ↑
           city wk met
'''

### Task 1 — ufuncs on real data

In [365]:
ratings = data[:, :, 2]
print(f'''
 Ratings: \n{ratings}
\n round upto 1 decimal: \n{ np.round(ratings, 1) }
\n sqrt: \n{ np.sqrt(ratings) }
\n log: \n{ np.log(ratings) }
\n Cap: cap elements >= 8 to 8. If element is 9.2, will be replaced by 8. if element < 8, no changes
{ np.clip(ratings, 1, 8) } 
''')

# no dtype changes for any of above operation


 Ratings: 
[[1.5 2.1 7.5 2.4]
 [5.3 3.  6.4 3.3]
 [2.2 9.1 9.2 1.5]
 [4.7 5.5 5.1 7.3]
 [0.4 1.4 5.3 9.2]]

 round upto 1 decimal: 
[[1.5 2.1 7.5 2.4]
 [5.3 3.  6.4 3.3]
 [2.2 9.1 9.2 1.5]
 [4.7 5.5 5.1 7.3]
 [0.4 1.4 5.3 9.2]]

 sqrt: 
[[1.22474487 1.44913767 2.73861279 1.54919334]
 [2.30217289 1.73205081 2.52982213 1.81659021]
 [1.4832397  3.01662063 3.03315018 1.22474487]
 [2.16794834 2.34520788 2.25831796 2.70185122]
 [0.63245553 1.18321596 2.30217289 3.03315018]]

 log: 
[[ 0.40546511  0.74193734  2.01490302  0.87546874]
 [ 1.66770682  1.09861229  1.85629799  1.19392247]
 [ 0.78845736  2.20827441  2.21920348  0.40546511]
 [ 1.54756251  1.70474809  1.62924054  1.98787435]
 [-0.91629073  0.33647224  1.66770682  2.21920348]]

 Cap: cap elements >= 8 to 8. If element is 9.2, will be replaced by 8. if element < 8, no changes
[[1.5 2.1 7.5 2.4]
 [5.3 3.  6.4 3.3]
 [2.2 8.  8.  1.5]
 [4.7 5.5 5.1 7.3]
 [1.  1.4 5.3 8. ]] 



### Task 2 — Aggregations with axis mastery

In [395]:
total_cost = data[:, :, 1].sum()
avg_delievery_time = data[:, :, 0].mean(axis=1)
best_rating_week = data[:, :, 2].max(axis=0)
avg_metrics = data.mean(axis= (0, 1) )
print(f'''
Total Cost: {total_cost.astype(int)}
Average delivery time per CITY: {avg_delievery_time}, {avg_delievery_time.shape}
Best Rating per Week across all cities: {best_rating_week}, {best_rating_week.shape}
Average of each METRIC across everything: {avg_metrics}, {avg_metrics.shape}

''')


Total Cost: 1080000
Average delivery time per CITY: [35.25  12.875 35.5   24.375 17.375], (5,)
Best Rating per Week across all cities: [5.3 9.1 9.2 9.2], (4,)
Average of each METRIC across everything: [2.5075e+01 5.4000e+04 4.6200e+00], (3,)




In [403]:
def calculate_delivery_score(data):
    scores = []
    for city in range(data.shape[0]):
        for week in range(data.shape[1]):
            time   = data[city, week, 0]
            cost   = data[city, week, 1]
            rating = data[city, week, 2]
            score  = (rating * 10) - (time * 0.5) - (cost * 0.001)
            scores.append(score)
    return np.array(scores)

start = time.perf_counter()
result_slow = calculate_delivery_score(data)
time_slow = time.perf_counter() - start
#score is the most expensive term here cus for each element, it has to check dtype bfore doing nay operation.


def calculate_delivery_score_fast(data):
    time   = data[:, :, 0]
    cost   = data[:, :, 1]
    rating = data[:, :, 2]
    scores  = (rating * 10) - (time * 0.5) - (cost * 0.001)
    return scores.ravel()

start = time.perf_counter()
result_fast = calculate_delivery_score_fast(data)
time_fast = time.perf_counter() - start

print(np.allclose(result_slow, result_fast))  # True
print(f"Slow: {time_slow:.6f}s")
print(f"Fast: {time_fast:.6f}s")
print(f"Speedup: {time_slow/time_fast:.0f}x")

True
Slow: 0.000116s
Fast: 0.000097s
Speedup: 1x


### Task 4 — Combining everything

In [431]:
avg_rating_per_city = data[:, :, 2].mean(axis=1)
best_city_avg_index = np.argmax(avg_rating_per_city) # while np.max finds highest element in the array, np.argmax file the index of the highest element of the array

avg_cost_week = data[:, :, 1].mean(axis=0)
least_avg_cost_week = np.argmin(avg_cost_week)

r_min = ratings.min()
r_max = ratings.max()
normalized = (ratings - r_min) / (r_max - r_min)

bad_combos = (data[:, :, 0] > 20) & (data[:, :, 2] < 5.0)

print(f'''
Highest AVERAGE rating CITY: { cities[best_city_avg_index] }
Lowest AVERAGE cost WEEK: {weeks[least_avg_cost_week]}
Normalized ratings: \n{normalized}
{ normalized.min() }, { normalized.max() }
\n{bad_combos.sum()}, {bad_combos.dtype}, {bad_combos.sum().dtype}
''')


Highest AVERAGE rating CITY: Peshawar
Lowest AVERAGE cost WEEK: Week3
Normalized ratings: 
[[0.125      0.19318182 0.80681818 0.22727273]
 [0.55681818 0.29545455 0.68181818 0.32954545]
 [0.20454545 0.98863636 1.         0.125     ]
 [0.48863636 0.57954545 0.53409091 0.78409091]
 [0.         0.11363636 0.55681818 1.        ]]
0.0, 1.0

8, bool, int32

